# (prometheus.yml 기준) ~/prometheus/prometheus-config/rule.yml 에 작성하는 내용

groups:
  - name: example1 # 파일 내에서 unique 해야함
    rules:

      # 어떤 인스턴스든 5분 이상 다운되어 있으면 감지한다.
      - alert: InstanceDown
        expr: up == 0
        for: 5m
        labels:
          severity: page
        annotations:
          summary: "Instance {{ $labels.instance }} down"
          description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes."

      # API 요청 지연시간(latency)의 중앙값(quantile 0.5)이 1초를 초과하는 액션이 10분 이상 지속되면 감지한다.
      - alert: APIHighRequestLatency
        expr: api_http_request_latencies_second{quantile="0.5"} > 1
        for: 10m
        annotations:
          summary: "High request latency on {{ $labels.instance }}"
          description: "{{ $labels.instance }} has a median request latency above 1s (current value: {{ $value }}s)"
