spring:
  datasource:
    url: jdbc:mysql://localhost:3306/${LOCAL_DB_NAME}?serverTimezone=UTC&characterEncoding=UTF-8
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create #TODO: 수정필요
    show-sql: true

logging:
  level:
    root: INFO
    com.swyp.artego: DEBUG