spring:
  datasource:
    url: jdbc:mysql://localhost:3306/${LOCAL_DB_NAME}?serverTimezone=UTC&characterEncoding=UTF-8
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: naver
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            redirect-uri: http://localhost:8000/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
              - mobile

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

#server:
#  servlet:
#    session:
#      timeout: 30m  # 세션 유지 시간 설정 (추후)

logging:
  level:
    root: INFO
    com.swyp.artego: DEBUG

