spring:
  datasource:
    url: jdbc:mysql://localhost:3306/${LOCAL_DB_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          naver:
            redirect-uri: http://localhost:8000/login/oauth2/code/naver

server:
  servlet:
    session:
      timeout: 30m  # 세션 유지 시간 설정 (추후)

logging:
  level:
    root: INFO
    com.swyp.artego: DEBUG
    org.springframework.web: DEBUG

