name: deploy

#TODO: 수정필요!!, 환경변수 입력 필요!!

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: "temurin"

      - name: Build with Gradle
        run: |
          ./gradlew bootJar

      - name: Docker Hub login
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker build & push to docker hub
        run: |
          docker build -t ${{ secrets.DOCKER_REPO }} .
          docker push ${{ secrets.DOCKER_REPO }}
  

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOSTNAME }}
          password: ${{ secrets.SSH_PWD }}
          script: |
            docker pull ${{ secrets.DOCKER_REPO }}
            cd EUM-Bank-docker
            echo "${{ secrets.BANK_ENV }}" > .env
            docker-compose up --build -d
            docker image prune -f --filter "until=24h"