name: Push Workflow (deploy)

on:
  push:
    branches:
      - main
      - dev
      - temp

jobs:
  docker-build-deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set Short Commit SHA
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Docker Hub Login
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_REPO }}:$SHORT_SHA .
          docker tag ${{ secrets.DOCKER_REPO }}:$SHORT_SHA ${{ secrets.DOCKER_REPO }}:latest

      - name: Push Docker Images
        run: |
          docker push ${{ secrets.DOCKER_REPO }}:$SHORT_SHA
          docker push ${{ secrets.DOCKER_REPO }}:latest

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.SSH_PWD }}
          script: |
            set -e
            docker pull ${{ secrets.DOCKER_REPO }}:$SHORT_SHA
            docker rm -f artego || true
            cd artego-server
            echo "${{ secrets.SPRING_ENV }}" > .env
            docker run -d --name artego -p ${{ secrets.APP_PORT_EXTERNAL_INTERNAL }} --env-file .env ${{ secrets.DOCKER_REPO }}:$SHORT_SHA
            docker image prune -f --filter "until=36h"